name: Build release

on:
  push:
    tags:
      - "v*.*.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Extract Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Executable
        run: |
          pip install pyinstaller
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller -i ./assets/icon.png --onefile gui.py --name TboiMM-${{ env.VERSION }}-windows.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller -i ./assets/icon.png --onefile gui.py --name TboiMM-${{ env.VERSION }}-macos
          else
            pyinstaller -i ./assets/icon.png --onefile gui.py --name TboiMM-${{ env.VERSION }}-linux
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/TboiMM-${{ env.VERSION }}-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/build-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
